#!/usr/bin/env bash
set -Eeuo pipefail
use std::log
use std::print

REPO="${PRJ_ROOT}"; # TODO: error if prj_root not set
DRY_RUN=false


FILES_SHOULD_EXIST=("README.md" "oranda.json" "Cargo.toml" "justfile")
FILES_TO_SYNC=(".gitignore" ".envrc" "renovate.json" "deny.toml" ".clippy.toml") # TODO: copy these from a template directory (and add files_should_exist files) instead of from proejct
FILES_TO_REMOVE=("LICENSE" "Cargo.lock" ".git" "flake.lock" "target" "result"  ".devenv" ".direnv" ".pre-commit-config.yaml" "public")
FILES_TO_WARN=("flake.nix") # TODO: rethink warning on these

function sync() {
  local source="$1"
  local dest="$1"
  if [[ -n "$dest" ]]; then
    log::warn "Syncing ${dest}"
    if [[ "${DRY_RUN}" == "true" ]]; then      
      echo "[dryrun] Copying ${source} ${dest}"
    else
      cp -r "${source}" "${dest}" 
    fi
  fi
}

function remove() {
  local file="$1"
  if [[ -f "${file}" ]]; then
    log::warn "Removing ${file}"
    if [[ "${DRY_RUN}" == "true" ]]; then      
      echo "[dryrun] Removing ${file}"
    else
      trash "${file}"
    fi
  fi
}

function warn_on_file() {
  local file="$1"
  if [[ -f "${file}" ]]; then
    log::warn "Review and delete ${file}"
  fi
}

function validate() {
  local manifest="$1"
  local dir_project_name="$2"
  local toml_project_name

  log::info "Validating ${manifest}"
  toml_project_name="$(toml-path --raw-output .package.name "${manifest}")"

  if [[ "${toml_project_name}" != "${dir_project_name}" ]]; then
    log::error "Cargo.toml project.name '${toml_project_name}' != directory name '${dir_project_name}'"
  fi
}

while [[ $# -gt 0 ]]; do
    arg="$1"
    case "${arg}" in
        -d|--dry-run)
            DRY_RUN=true
            log::warn "dry-run enabled"
            ;;
        *)
            echo "Unknown option: ${arg}"
            exit 2
            ;;
    esac
    shift
done


for crate in "${REPO}/crates/"*; do
  manifest="${crate}/Cargo.toml"
  dir_project_name="$(basename "${crate}")"

  print::status "Checking ${crate}"


  # Copy boilerplate files to each crate if they are missing
  print::substatus "Copying boilerplate files"
  for file in "${FILES_TO_SYNC[@]}"; do
    source="${REPO}/${file}"
    dest="${crate}/${file}"
    sync "${source}" "${dest}"
  done

  # Remove files that don't belong in the mono-crate
  print::substatus "Removing unnecessary files"
  for file in "${FILES_TO_REMOVE[@]}"; do
    remove "${crate}/${file}"
  done

  # Warn about files that may require manual attention before removal
  for file in "${FILES_TO_WARN[@]}"; do
    warn_on_file "${crate}/${file}"
  done
  
  # Standardize licenses
  print::substatus "Standardizing licences"
  cp "${REPO}/LICENSE-APACHE" "${crate}/"
  cp "${REPO}/LICENSE-MIT" "${crate}/"

  
  # Validate files exist
  log::info "Validating files exist"
  for file in "${FILES_SHOULD_EXIST[@]}"; do
    path="${crate}/${file}"
    if [[ ! -f "${path}" ]]; then
      log::error "Expected ${path}, but file does not exist"
    fi
  done

  # Validate crates
  print::substatus "Validating manifests"
  validate "${manifest}" "${dir_project_name}"


  echo ''

done
